// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetConfig():Promise<types.GuiResponse>;

export function GetStatus():Promise<types.GuiResponse>;

export function SetChatCompletionConfig(arg1:types.CompletionConfigRequest):Promise<types.GuiResponse>;

export function SetCodeCompletionConfig(arg1:types.CompletionConfigRequest):Promise<types.GuiResponse>;

export function SetSystemConfig(arg1:types.SystemConfigRequest):Promise<types.GuiResponse>;

export function Start():Promise<types.GuiResponse>;

export function Stop():Promise<types.GuiResponse>;
