// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['gui']['GuiHandler']['GetConfig']();
}

export function GetStatus() {
  return window['go']['gui']['GuiHandler']['GetStatus']();
}

export function SetChatCompletionConfig(arg1) {
  return window['go']['gui']['GuiHandler']['SetChatCompletionConfig'](arg1);
}

export function SetCodeCompletionConfig(arg1) {
  return window['go']['gui']['GuiHandler']['SetCodeCompletionConfig'](arg1);
}

export function SetSystemConfig(arg1) {
  return window['go']['gui']['GuiHandler']['SetSystemConfig'](arg1);
}

export function Start() {
  return window['go']['gui']['GuiHandler']['Start']();
}

export function Stop() {
  return window['go']['gui']['GuiHandler']['Stop']();
}
